version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: InsuranceAPI
    environment:
      POSTGRES_USER: gaguirre
      POSTGRES_PASSWORD: gaguirre
      POSTGRES_DB: InsuranceDB
    ports:
      - "5432:5432"
